name: React with Vite

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 24

    - run: corepack enable pnpm

    - run: pnpm install

    - run: pnpm build

    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages
